- name: Home
  width: wide
  head-widgets:
    - type: markets
      hide-header: true
      markets:
        - symbol: SPY
          name: S&P 500
        - symbol: EUR=X
          name: USD/EUR
        - symbol: NVDA
          name: NVIDIA
    - type: to-do
  
  columns:
    - size: full
      widgets:
        - type: split-column
          max-columns: 5
          widgets:
            - subreddit: news
              <<: *subreddit-settings
            - type: hacker-news
              collapse-after: 15
            - type: lobsters
              sort-by: hot
              limit: 15
              collapse-after: 15
            - title: Marginal Revolution
              feeds:
                - url: https://www.marginalrevolution.com/feed
                  <<: *feed-settings
              <<: *rss-settings
            - title: Blogs
              feeds:
                - url: http://astralcodexten.substack.com/feed
                  <<: *feed-settings
                - url: https://thezvi.wordpress.com/feed/
                  <<: *feed-settings
                - url: https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine.rss
                  <<: *feed-settings
                - url: https://www.overcomingbias.com/feed
                  <<: *feed-settings
              <<: *rss-settings
            - subreddit: science
              <<: *subreddit-settings
            - subreddit: foodforthought
              <<: *subreddit-settings
            - title: Slashdot
              feeds:
                - url: https://rss.slashdot.org/Slashdot/slashdot
                  <<: *feed-settings
              css-class: widget-slashdot
              <<: *rss-settings
            - title: Lesswrong (Curated)
              style: vertical-list
              feeds:
                - url: https://www.lesswrong.com/feed.xml?view=curated-rss
                  headers:
                    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
                  <<: *feed-settings
              <<: *rss-settings
            - title: Lesswrong (Frontpage)
              style: vertical-list
              feeds:
                - url: https://www.lesswrong.com/feed.xml?view=frontpage-rss&karmaThreshold=75
                  headers:
                    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
                  <<: *feed-settings
              <<: *rss-settings
            - subreddit: technology
              <<: *subreddit-settings
            - subreddit: worldnews
              <<: *subreddit-settings
            - subreddit: economics
              <<: *subreddit-settings
            - subreddit: slatestarcodex
              <<: *subreddit-settings
            - subreddit: truereddit
              <<: *subreddit-settings
            - subreddit: wikipedia
              <<: *subreddit-settings
            # - title: Ars Technica
            #   style: detailed-list
            #   feeds:
            #     - url: https://feeds.arstechnica.com/arstechnica/index
            #       <<: *feed-settings
            #   <<: *rss-settings
            # - subreddit: selfhosted
            #   <<: *subreddit-settings
            # - subreddit: homelab
            #   <<: *subreddit-settings
            # - subreddit: linux
            #   <<: *subreddit-settings
            # - subreddit: sysadmin
            #   <<: *subreddit-settings
            # - subreddit: DevOps
            #   <<: *subreddit-settings
            # - subreddit: Networking
            #   <<: *subreddit-settings
